using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace DMM.Pages
{
    public partial class AnaylisisPage : DevExpress.XtraEditors.XtraUserControl
    {
        DBDMMEntities db;

        public AnaylisisPage()
        {
            InitializeComponent();

            SupplierGetData();
            CustomerGetData();
            TotalDebitGetData();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            DMM.DBDMMEntities dbContext = new DMM.DBDMMEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Debit_Customer.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                chartControl1.DataSource = dbContext.Debit_Customer.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        //private void SupplierGetData()
        //{
        //    try
        //    {
        //        db = new DBDMMEntities();
        //        var data = db.TB_Suppliers.Select(x => x.Debit).ToArray().Sum();
        //        txt_suppleir.Text = data.ToString();
        //    }
        //    catch { }
        //}

        //private void CustomerGetData()
        //{
        //    try
        //    {
        //        db = new DBDMMEntities();
        //        var data = db.TB_Customers.Select(x => x.Debit).ToArray().Sum();
        //        txt_customer.Text = data.ToString();
        //    }
        //    catch { }
        //}

        //private void TotalDebitGetData()
        //{
        //    try
        //    {
        //        db = new DBDMMEntities();
        //        var data1 = db.TB_Customers.Select(x => x.Debit).ToArray().Sum();
        //        var data2 = db.TB_Customers.Select(x => x.Debit).ToArray().Sum();
        //        txt_totoaldebit.Text = (data1 + data2).ToString();
        //    }
        //    catch { }
        //}
        private void SupplierGetData()
        {
            try
            {
                db = new DBDMMEntities();
                var data = db.TB_Suppliers.Select(x => x.Debit).ToArray().Sum();
                txt_suppleir.Text = data.ToString() + " د.ع";

            }
            catch { }
        }
        private void CustomerGetData()
        {
            try
            {
                db = new DBDMMEntities();
                var data = db.TB_Customers.Select(x => x.Debit).ToArray().Sum();
                txt_customer.Text = data.ToString() + " د.ع";

            }
            catch { }
        }
        private void TotalDebitGetData()
        {
            try
            {
                db = new DBDMMEntities();
                var data1 = db.TB_Suppliers.Select(x => x.Debit).ToArray().Sum();
                var data2 = db.TB_Customers.Select(x => x.Debit).ToArray().Sum();
                txt_totoaldebit.Text = (data1 + data2).ToString() + " د.ع";

            }
            catch { }
        }


    }
}
